# 线上配置文件
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zbbidb
    username: root
    password: sqlpassword
    # Redis 配置
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 5000
      password: localredis
    # mq配置
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  #接口文档
  knife4j:
    # 开启生产环境屏蔽
    production: false
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''